### ISSUE TITLE
新增配置可能会出现问题

### ISSUE THREAD

**Issue by Jayin** [Jayin/webhook#11]
重现：
1. 新增一份配置，配置写错了
2. 修改为正确的仍然说找不到webhook配置
3. 重新启动应用就好了

![image](https://cloud.githubusercontent.com/assets/2763894/15214176/26c72aaa-187e-11e6-9669-982f5ee9c2a1.png)

**Comment by fritx** [comment]
或者require前清缓存？ `delete require.cache[require.resolve('./b.js')]`
http://stackoverflow.com/questions/9210542/node-js-require-cache-possible-to-invalidate
